# Generated by Django 5.2.7 on 2025-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
