# Generated by Django 5.2.7 on 2025-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0002_department_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='sex',
            field=models.CharField(default='Herr', max_length=10),
            preserve_default=False,
        ),
    ]
