# Generated by Django 5.2.7 on 2025-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0003_professor_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='sex',
            field=models.CharField(choices=[('F', 'Frau'), ('M', 'Herr')], max_length=1),
        ),
    ]
