# Generated by Django 5.2.7 on 2025-10-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0004_alter_professor_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='sex',
            field=models.CharField(choices=[('Frau', 'Frau'), ('Herr', 'Herr')], max_length=10),
        ),
    ]
