# Generated by Django 5.2.7 on 2025-10-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0005_alter_professor_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
