# Generated by Django 5.2.7 on 2025-10-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('rating_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('current', 'Currently attending'), ('completed', 'Completed')], default='completed', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rmp.tag'),
        ),
        migrations.CreateModel(
            name='RatingScore',
            fields=[
                ('rating_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp.ratingcategory')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmp.rating')),
            ],
        ),
    ]
