# Generated by Django 5.2.7 on 2025-10-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0007_ratingcategory_remove_rating_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcategory',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ratingscore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rmp.ratingcategory'),
        ),
        migrations.AlterField(
            model_name='ratingscore',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rmp.rating'),
        ),
        migrations.AlterField(
            model_name='ratingscore',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
